### ISSUE TITLE
ValueError and TypeError

### ISSUE THREAD

**Issue by derjoern** [kofec/Domoticz-Enigma2#5]
Hi there!

I'm running your plugin on Debian Buster with python 3.7 and get several errors on startup and while running:

Oct 12 09:09:12 smarthome domoticz: (VU Uno 4K) 'onStart' failed 'ValueError':'invalid literal for int() with base 10: '''.
Oct 12 09:09:12 smarthome domoticz: (VU Uno 4K) ----> Line 414 in '/opt/domoticz/plugins/Domoticz-Enigma2/plugin.py', function onStart
Oct 12 09:09:12 smarthome domoticz: (VU Uno 4K) ----> Line 213 in '/opt/domoticz/plugins/Domoticz-Enigma2/plugin.py', function onStart
Oct 12 09:09:22 smarthome domoticz: (VU Uno 4K) 'onHeartbeat' failed 'TypeError'.
Oct 12 09:09:22 smarthome domoticz: (VU Uno 4K) ----> Line 449 in '/opt/domoticz/plugins/Domoticz-Enigma2/plugin.py', function onHeartbeat
Oct 12 09:09:22 smarthome domoticz: (VU Uno 4K) ----> Line 349 in '/opt/domoticz/plugins/Domoticz-Enigma2/plugin.py', function onHeartbeat
Oct 12 09:09:22 smarthome domoticz: (VU Uno 4K) ----> Line 247 in '/opt/domoticz/plugins/Domoticz-Enigma2/plugin.py', function isAlive
Oct 12 09:09:32 smarthome domoticz: (VU Uno 4K) 'onHeartbeat' failed 'TypeError'.

The ValueError appears only at startup while the TypeError shows up every 10 seconds.

**Comment by kofec** [comment]
Please chaeck if you have python3 package xmltodict. 
Second thing is please check if you have fill in "Poll Period (* 10s):" on "Configuration -> Hardware" tab

**Comment by derjoern** [comment]
Hi!

xmltodict was installed, but the poll period was empty. Set it to 20 and now the error log is slient.

Thanks for your help!

**Comment by kofec** [comment]
So I close this ticket
